// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: rate.proto

package ratepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RoutingServiceClient is the client API for RoutingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoutingServiceClient interface {
	GetRate(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (RoutingService_GetRateClient, error)
}

type routingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutingServiceClient(cc grpc.ClientConnInterface) RoutingServiceClient {
	return &routingServiceClient{cc}
}

func (c *routingServiceClient) GetRate(ctx context.Context, in *RateRequest, opts ...grpc.CallOption) (RoutingService_GetRateClient, error) {
	stream, err := c.cc.NewStream(ctx, &RoutingService_ServiceDesc.Streams[0], "/ratepb.RoutingService/GetRate", opts...)
	if err != nil {
		return nil, err
	}
	x := &routingServiceGetRateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RoutingService_GetRateClient interface {
	Recv() (*RateResponse, error)
	grpc.ClientStream
}

type routingServiceGetRateClient struct {
	grpc.ClientStream
}

func (x *routingServiceGetRateClient) Recv() (*RateResponse, error) {
	m := new(RateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RoutingServiceServer is the server API for RoutingService service.
// All implementations must embed UnimplementedRoutingServiceServer
// for forward compatibility
type RoutingServiceServer interface {
	GetRate(*RateRequest, RoutingService_GetRateServer) error
	mustEmbedUnimplementedRoutingServiceServer()
}

// UnimplementedRoutingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRoutingServiceServer struct {
}

func (UnimplementedRoutingServiceServer) GetRate(*RateRequest, RoutingService_GetRateServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRate not implemented")
}
func (UnimplementedRoutingServiceServer) mustEmbedUnimplementedRoutingServiceServer() {}

// UnsafeRoutingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutingServiceServer will
// result in compilation errors.
type UnsafeRoutingServiceServer interface {
	mustEmbedUnimplementedRoutingServiceServer()
}

func RegisterRoutingServiceServer(s grpc.ServiceRegistrar, srv RoutingServiceServer) {
	s.RegisterService(&RoutingService_ServiceDesc, srv)
}

func _RoutingService_GetRate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RoutingServiceServer).GetRate(m, &routingServiceGetRateServer{stream})
}

type RoutingService_GetRateServer interface {
	Send(*RateResponse) error
	grpc.ServerStream
}

type routingServiceGetRateServer struct {
	grpc.ServerStream
}

func (x *routingServiceGetRateServer) Send(m *RateResponse) error {
	return x.ServerStream.SendMsg(m)
}

// RoutingService_ServiceDesc is the grpc.ServiceDesc for RoutingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoutingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ratepb.RoutingService",
	HandlerType: (*RoutingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRate",
			Handler:       _RoutingService_GetRate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rate.proto",
}
